# Generated by Django 5.0.4 on 2024-08-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('undefined', 'Không xác định')], max_length=100),
        ),
    ]
