# Generated by Django 5.1.2 on 2025-03-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_shippingaddress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postal_code',
        ),
    ]
