# Generated by Django 5.1.2 on 2025-04-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_shippingaddress_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line_2',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(default='dctrng@gmail.com', max_length=254),
        ),
    ]
